### ISSUE TITLE
possible missing default headers

### ISSUE THREAD

**Issue by MrAliSalehi** [Gelbpunkt/tokio-websockets#76]
Im trying to connect to discord gateway: 
`wss://gateway.discord.gg/?v=3&encoding=json`

using any other library in (including other languages) im able to just do something like `Client::connect(endpoint)` with essentially nothing else, and get a response back (200 containing initial info) from the discord.

but currently `tokio_websockets` is missing some headers or mis-interpreting something, the reason being that discord returns `Bad Request` and the library throws `DidNotSwitchProtocols` when I call `connect`, again , same request, nothing different.
so, any help would be appreciated

**Comment by Gelbpunkt** [comment]
Hi, this may be because you're trying to connect to gateway version 3, which doesn't exist anymore. I recommend looking at the source code of [twilight](https://docs.rs/twilight-gateway) for specifics, particularly here: https://github.com/twilight-rs/twilight/blob/main/twilight-gateway/src/shard.rs#L759
That said, this isn't a bug within the websocket library itself, but rather a question of where you're connecting to, so I'm going to close this issue.

**Comment by MrAliSalehi** [comment]
i tested different versions, thats not the problem otherwise it would throw invalid version

**Comment by Erk-** [comment]
> i tested different versions, thats not the problem otherwise it would throw invalid version

Can you provide some code that makes this happen (also include your Cargo.toml)

**Comment by MrAliSalehi** [comment]
i managed to solve the issue by using webpki tls feature flag, it seems that discord doesnt accept plain connections in anyway
